### ISSUE TITLE
'DataFrame' object has no attribute 'ix' index

### ISSUE THREAD

**Issue by SridharJagannathan** [schlegelp/pymaid#201]
Error when plotting a neuron with connectors like below:
```
catmiad_neuron=pymaid.get_neurons(['6180224'],remote_instance = working_rm)
fig = catmiad_neuron.plot3d(backend='plotly', connectors=True, width=1400)
```
On further debugging, it seems the pandas has deprecated `ix` in favor of `iloc` and `loc` , see here:
https://github.com/schlegelp/pymaid/blob/839863a523949ec64f1fa7112db558943ddc9adb/pymaid/plotting.py#L1316
in this context it would be best to update this like 
`tn = neuron.nodes.set_index('treenode_id').loc[this_cn.treenode_id.values]`

**Comment by schlegelp** [comment]
This is already fixed in the `dev` branch - I just haven't gotten around merging it as it is a major break with past versions in that it bases `pymaid` on `navis`. 

I would recommend you install navis from Github and use pymaid's `dev` branch for now. That would also help me iron out some of the remaining kinks before merging `dev` into `master`.

**Comment by schlegelp** [comment]
pymaid 2.0.1 is now on master and has this issue fixed. Installation now also possible from PyPI: `pip3 install python-catmaid`
