### ISSUE TITLE
nblast_allbyall reports error if a neuronlist is resampled

### ISSUE THREAD

**Issue by zhihaozheng** [schlegelp/pyMaid#55]
A minimal example:
`nl = pymaid.get_neuron('annotation:glomerulus DA1')`
`nl.resample(1000, inplace=True)`
`res = rmaid.nblast_allbyall( nl )`

Additionally, my understanding is, since the nblast algorithm looks for cloud vectors in partner neurons, resample is alway preferred for nblasting since otherwise nodes with uneven intervals could mess up interpretation of distance between pairs.

**Comment by jefferis** [comment]
Not sure how pymaid handles the nm/micron transition. Is that an issue here?

**Comment by schlegelp** [comment]
@zhihaozheng turns out when resampling the data type of treenode IDs changes from native `int` to numpy `int64` which somehow upset the converter to R objects. I've pushed a new version - please update and let me know if that fixes it for you.

The reason why I never encountered that bug is that you don't have to resample before nblasting: this is done automatically when converting to dotprops. I've made this explicit in the docstring now. For reference: I'm following the code of [nblast_fafb](https://github.com/jefferis/elmr/blob/68e5ab3c2736b919a6faa42b46bb5e1d697a80b8/R/nblast_fafb.R).

**Comment by schlegelp** [comment]
Oh and forgot: @jefferis, if I'm not mistaken `nat:xform_brain` from FAFB to light level should take care of conversion from nm to microns, no?

**Comment by jefferis** [comment]
Yes it does.

**Comment by zhihaozheng** [comment]
Just tested it. Yes, the newest version fixed it. Sorry for the delay.

**Comment by schlegelp** [comment]
Cool, thanks. I'm closing this issue. For future reference: fixed in c23603c6091d7bc0dbbbfe8a733411d6bed837e5
